name: Payload Dumper Image

on:
  workflow_dispatch:
    inputs:
      Tool_Link:
        description: 'Tool_Link'
        required: false
        default: 'https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz'
      Rom_Link:
        description: 'Rom_Link'
        required: true
        default: ''
      Zip_name:
        description: 'Zip_name'
        required: true
        default: ''
      Image_name:
        description: 'Image_name'
        required: true
        default: ''
       
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: ğŸ’¥ Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: ğŸ’¥ Check Out
      uses: actions/checkout@main

    - name: ğŸ’¥ Set Variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var

    - name: ğŸ’¥ Download Tools
      run: |
        export HOME=${GITHUB_WORKSPACE}
        mkdir -p ${GITHUB_WORKSPACE}/workspace && cd ${GITHUB_WORKSPACE}/workspace
        wget "${{ github.event.inputs.Tool_Link }}" -O ./payload-dumper.tar.gz
        tar -zxvf ./payload-dumper.tar.gz

    - name: ğŸ’¥ Install 7-Zip and transfer
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        mkdir -p 7-zip && cd 7-zip
        wget "https://jaist.dl.sourceforge.net/project/sevenzip/7-Zip/22.01/7z2201-linux-x64.tar.xz" -O "7z2201-linux-x64.tar.xz"
        sudo chmod 0777 "7z2201-linux-x64.tar.xz"
        tar -xf "7z2201-linux-x64.tar.xz"
        sudo chmod 0777 ./7zzs
        sudo cp ./7zzs /usr/local/bin/7z
        7z --help
        cd /usr/local/bin
        sudo curl -sL https://raw.githubusercontent.com/Mikubill/transfer/master/install.sh | bash
        sudo chmod 0777 transfer
        
    - name: ğŸ’¥ Download Rom
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        sudo apt-get install axel
        axel -n 16 "${{ github.event.inputs.Rom_Link }}" -o ./${{ github.event.inputs.Zip_name }}.zip
        unzip ./${{ github.event.inputs.Zip_name }}.zip
        ls -la ./*

    - name: ğŸ’¥ Start Dumper Image
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        echo -e "åœ¨ payload.bin ä¸­æ˜¾ç¤ºåˆ†åŒºåˆ—è¡¨\n"
        ./payload-dumper-go -l payload.bin
        echo -e "å¼€å§‹æå–é•œåƒ...\n"
        ./payload-dumper-go -o ${GITHUB_WORKSPACE}/workspace/out -p ${{ github.event.inputs.Image_name }} payload.bin
        echo -e "è·å–é•œåƒçš„md5...\n"
        cd ${GITHUB_WORKSPACE}/workspace/out
        md5sum * | tee ${GITHUB_WORKSPACE}/workspace/out/md5sum.txt
        echo -e "è·å–é•œåƒçš„sha256...\n"
        sha256sum * | tee ${GITHUB_WORKSPACE}/workspace/out/sha256sum.txt
        time="2009-01-01 08:00:00"
        find ./ * -exec touch -m -d "$time" {} \;
        echo -e "æ•´åˆä¸ºå‹ç¼©åŒ…(7zip)...\n"
        7z a -t7z -m0=lzma2 -mx=9 -mmt=$(nproc --all) ${{ github.event.inputs.Zip_name }}-${{ github.event.inputs.Image_name }}.7z ./*

    - name: ğŸ’¥ Upload Transfer
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/out
        sudo chmod -R 0777 ${GITHUB_WORKSPACE}/workspace
        transfer wet ./${{ github.event.inputs.Zip_name }}-${{ github.event.inputs.Image_name }}.7z
